CMX.CPLegacyStrings = {
    ["de"] = {
        [1] = {
            [1] = "Fokus zerschlagen",
            [2] = "Sprinter",
            [3] = "Absauger",
            [4] = "Kriegsherr",
            [5] = "Verlangsamen",
            [6] = "Inspiration",
            [7] = "Maras Gabe",
            [8] = "Streitross",
            ["name"] = "Der Turm",
        },
        [2] = {
            [1] = "Fokus auf schwere Rüstung",
            [2] = "Bastion",
            [3] = "Verteidigungsexperte",
            [4] = "Schnelle Erholung",
            [5] = "Feldarzt",
            [6] = "Infusion",
            [7] = "Aufleben",
            [8] = "Tapferkeit",
            ["name"] = "Der Fürst",
        },
        [3] = {
            [1] = "Fokus auf leichte Rüstung",
            [2] = "Dickhäutig",
            [3] = "Abgehärtet",
            [4] = "Elementarverteidiger",
            [5] = "Zauberabsorption",
            [6] = "Bollwerk",
            [7] = "Kritisches Entziehen",
            [8] = "Entfesselt",
            ["name"] = "Die Fürstin",
        },
        [4] = {
            [1] = "Fokus auf mittlere Rüstung",
            [2] = "Unangreifbar",
            [3] = "Magieschild",
            [4] = "Resistent",
            [5] = "Erfrischender Hieb",
            [6] = "Phase",
            [7] = "Ausdauernd",
            [8] = "Verstärkt",
            ["name"] = "Das Schlachtross",
        },
        [5] = {
            [1] = "Thaumaturg",
            [2] = "Präzise Schläge",
            [3] = "Durchdringend",
            [4] = "Kräftig",
            [5] = "Opportunist",
            [6] = "Perfekter Schlag",
            [7] = "Ausnutzer",
            [8] = "Letztes Aufbäumen",
            ["name"] = "Das Ritual",
        },
        [6] = {
            [1] = "Experte für physische Waffen",
            [2] = "Berstende Hiebe",
            [3] = "Waffenmeister",
            [4] = "Stabexperte",
            [5] = "Vergeltung",
            [6] = "Erwidern",
            [7] = "Schlachter",
            [8] = "Taktiker",
            ["name"] = "Der Atronach",
        },
        [7] = {
            [1] = "Elementarexperte",
            [2] = "Magieerosion",
            [3] = "Elfenblut",
            [4] = "Gesegnet",
            [5] = "Rache",
            [6] = "Magiepräzision",
            [7] = "Vorblick",
            [8] = "Arkane Quelle",
            ["name"] = "Der Lehrling",
        },
        [8] = {
            [1] = "Verdorben",
            [2] = "Schatten",
            [3] = "Schattenhafter Schutz",
            [4] = "Gelenkigkeit",
            [5] = "Glücksritter",
            [6] = "Händlerliebling",
            [7] = "Schatzjäger",
            [8] = "Schattenschlag",
            ["name"] = "Der Schatten",
        },
        [9] = {
            [1] = "Mondkalb",
            [2] = "Arkanist",
            [3] = "Gesund",
            [4] = "Tenazität",
            [5] = "Reichlicher Ertrag",
            [6] = "Synergetiker",
            [7] = "Meistersammler",
            [8] = "Windlaufen",
            ["name"] = "Die Liebende",
        },
    },
    ["en"] = {
        [1] = {
            [1] = "Bashing Focus",
            [2] = "Sprinter",
            [3] = "Siphoner",
            [4] = "Warlord",
            [5] = "Ensnare",
            [6] = "Inspiration Boost",
            [7] = "Mara's Gift",
            [8] = "War Mount",
            ["name"] = "The Tower",
        },
        [2] = {
            [1] = "Heavy Armor Focus",
            [2] = "Bastion",
            [3] = "Expert Defender",
            [4] = "Quick Recovery",
            [5] = "Field Physician",
            [6] = "Infusion",
            [7] = "Revival",
            [8] = "Determination",
            ["name"] = "The Lord",
        },
        [3] = {
            [1] = "Light Armor Focus",
            [2] = "Thick Skinned",
            [3] = "Hardy",
            [4] = "Elemental Defender",
            [5] = "Spell Absorption",
            [6] = "Bulwark",
            [7] = "Critical Leech",
            [8] = "Unchained",
            ["name"] = "The Lady",
        },
        [4] = {
            [1] = "Medium Armor Focus",
            [2] = "Ironclad",
            [3] = "Spell Shield",
            [4] = "Resistant",
            [5] = "Invigorating Bash",
            [6] = "Phase",
            [7] = "Resilient",
            [8] = "Reinforced",
            ["name"] = "The Steed",
        },
        [5] = {
            [1] = "Thaumaturge",
            [2] = "Precise Strikes",
            [3] = "Piercing",
            [4] = "Mighty",
            [5] = "Opportunist",
            [6] = "Perfect Strike",
            [7] = "Exploiter",
            [8] = "Last Stand",
            ["name"] = "The Ritual",
        },
        [6] = {
            [1] = "Physical Weapon Expert",
            [2] = "Shattering Blows",
            [3] = "Master-at-Arms",
            [4] = "Staff Expert",
            [5] = "Retaliation",
            [6] = "Riposte",
            [7] = "Butcher",
            [8] = "Tactician",
            ["name"] = "The Atronach",
        },
        [7] = {
            [1] = "Elemental Expert",
            [2] = "Spell Erosion",
            [3] = "Elfborn",
            [4] = "Blessed",
            [5] = "Vengeance",
            [6] = "Spell Precision",
            [7] = "Foresight",
            [8] = "Arcane Well",
            ["name"] = "The Apprentice",
        },
        [8] = {
            [1] = "Befoul",
            [2] = "Shade",
            [3] = "Shadow Ward",
            [4] = "Tumbling",
            [5] = "Fortune Seeker",
            [6] = "Merchant Favored",
            [7] = "Treasure Hunter",
            [8] = "Shadowstrike",
            ["name"] = "The Shadow",
        },
        [9] = {
            [1] = "Mooncalf",
            [2] = "Arcanist",
            [3] = "Healthy",
            [4] = "Tenacity",
            [5] = "Plentiful Harvest",
            [6] = "Synergizer",
            [7] = "Master Gatherer",
            [8] = "Windrunning",
            ["name"] = "The Lover",
        },
    },
    ["fr"] = {
        [1] = {
            [1] = "Focalisation d'éclatage",
            [2] = "Sprinteur",
            [3] = "Siphonage",
            [4] = "Seigneur de guerre",
            [5] = "Prise au collet",
            [6] = "Regain d'inspiration",
            [7] = "Don de Mara",
            [8] = "Monture de guerre",
            ["name"] = "La Tour",
        },
        [2] = {
            [1] = "Spécialisation armure lourde",
            [2] = "Bastion",
            [3] = "Expertise de la défense",
            [4] = "Récupération rapide",
            [5] = "Médecin du front",
            [6] = "Infusion",
            [7] = "Retour en grâce",
            [8] = "Résilience",
            ["name"] = "Le Seigneur",
        },
        [3] = {
            [1] = "Spécialisation armure légère",
            [2] = "Peau dure",
            [3] = "Robuste",
            [4] = "Défenseur élémentaire",
            [5] = "Absorption magique",
            [6] = "Rempart",
            [7] = "Sangsue critique",
            [8] = "Déchaîné",
            ["name"] = "La Dame",
        },
        [4] = {
            [1] = "Spécialisation armure moyenne",
            [2] = "Cuirassé",
            [3] = "Bouclier anti-sorts",
            [4] = "Résistant",
            [5] = "Percussion revigorante",
            [6] = "Phase",
            [7] = "Résistance",
            [8] = "Renforcé",
            ["name"] = "Le Destrier",
        },
        [5] = {
            [1] = "Thaumaturge",
            [2] = "Frappes précises",
            [3] = "Percée",
            [4] = "Puissance",
            [5] = "Opportuniste",
            [6] = "Visée parfaite",
            [7] = "Exploiteur",
            [8] = "Récupération",
            ["name"] = "Le Rituel",
        },
        [6] = {
            [1] = "Expertise en armes physiques",
            [2] = "Coups écrasants",
            [3] = "Capitaine d'armes",
            [4] = "Expertise en bâtons",
            [5] = "Représailles",
            [6] = "Riposte",
            [7] = "Boucher",
            [8] = "Tactique",
            ["name"] = "L’Atronach",
        },
        [7] = {
            [1] = "Expertise élémentaire",
            [2] = "Érosion magique",
            [3] = "Sang elfique",
            [4] = "Bénédiction",
            [5] = "Vengeance",
            [6] = "Précision des sorts",
            [7] = "Prévoyance",
            [8] = "Puits arcanique",
            ["name"] = "L’Apprenti",
        },
        [8] = {
            [1] = "Souillure",
            [2] = "Ombres",
            [3] = "Garde des ombres",
            [4] = "Acrobate",
            [5] = "Chercheur de fortune",
            [6] = "Relations commerciales",
            [7] = "Chasseur de trésors",
            [8] = "Frappe d'ombre",
            ["name"] = "L’Ombre",
        },
        [9] = {
            [1] = "Inconscience",
            [2] = "Arcaniste",
            [3] = "Bonne santé",
            [4] = "Ténacité",
            [5] = "Moisson abondante",
            [6] = "Synergiste",
            [7] = "Maître de la cueillette",
            [8] = "Pied léger",
            ["name"] = "L’Amant",
        },
    },
    ["ru"] = {
        [1] = {
            [1] = "Сосредоточенные удары",
            [2] = "Спринтер",
            [3] = "Поглотитель",
            [4] = "Военачальник",
            [5] = "Замедление",
            [6] = "Прилив вдохновения",
            [7] = "Подарок Мары",
            [8] = "Боевое верховое животное",
            ["name"] = "Башня",
        },
        [2] = {
            [1] = "Уклон в тяжелые доспехи",
            [2] = "Бастион",
            [3] = "Опытный защитник",
            [4] = "Быстрое восстановление",
            [5] = "Полевой врач",
            [6] = "Вливание",
            [7] = "Воскрешение",
            [8] = "Целеустремленность",
            ["name"] = "Лорд",
        },
        [3] = {
            [1] = "Уклон в легкие доспехи",
            [2] = "Толстокожесть",
            [3] = "Крепость тела",
            [4] = "Стихийный защитник",
            [5] = "Поглощение заклинаний",
            [6] = "Оплот",
            [7] = "Критическое высасывание",
            [8] = "Неукротимость",
            ["name"] = "Леди",
        },
        [4] = {
            [1] = "Уклон в средние доспехи",
            [2] = "Железная оболочка",
            [3] = "Колдовской щит",
            [4] = "Упорство",
            [5] = "Воодушевляющий удар",
            [6] = "Фаза",
            [7] = "Жизнерадостность",
            [8] = "Прочность",
            ["name"] = "Конь",
        },
        [5] = {
            [1] = "Тауматург",
            [2] = "Точные удары",
            [3] = "Пробитие",
            [4] = "Могущество",
            [5] = "Нос по ветру",
            [6] = "Идеальный удар",
            [7] = "Добиватель",
            [8] = "Последняя надежда",
            ["name"] = "Ритуал",
        },
        [6] = {
            [1] = "Эксперт физического оружия",
            [2] = "Раскалывающие удары",
            [3] = "Мастер оружия",
            [4] = "Мастер владения посохом",
            [5] = "Возмездие",
            [6] = "Ответный удар",
            [7] = "Мясник",
            [8] = "Тактик",
            ["name"] = "Атронах",
        },
        [7] = {
            [1] = "Знаток стихий",
            [2] = "Колдовская эрозия",
            [3] = "Эльфийская кровь",
            [4] = "Благословение",
            [5] = "Месть",
            [6] = "Точные заклинания",
            [7] = "Предсказание",
            [8] = "Волшебный источник",
            ["name"] = "Ученик",
        },
        [8] = {
            [1] = "Осквернение",
            [2] = "Полумрак",
            [3] = "Оберег тени",
            [4] = "Прыгучесть",
            [5] = "Искатель богатств",
            [6] = "Благосклонность торговца",
            [7] = "Охотник за сокровищами",
            [8] = "Удар тени",
            ["name"] = "Тень",
        },
        [9] = {
            [1] = "Неуемная энергия",
            [2] = "Колдун",
            [3] = "Крепкое здоровье",
            [4] = "Цепкость",
            [5] = "Обильный урожай",
            [6] = "Мастер синергии",
            [7] = "Опытный собиратель",
            [8] = "На крыльях ветра",
            ["name"] = "Любовник",
        },
    },
}